#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
<<<<<<< HEAD
# Generated by Vivado on Wed Jun 04 16:54:48 MDT 2025
=======
# Generated by Vivado on Wed Jun 04 10:23:13 MDT 2025
>>>>>>> origin/master
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto d4dbb68866ff4b9180950033100825b1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot adc_to_udp_stream_v1_0_tb_behav xil_defaultlib.adc_to_udp_stream_v1_0_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto d4dbb68866ff4b9180950033100825b1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot adc_to_udp_stream_v1_0_tb_behav xil_defaultlib.adc_to_udp_stream_v1_0_tb xil_defaultlib.glbl -log elaborate.log

