#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jun 04 10:23:15 MDT 2025
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim adc_to_udp_stream_v1_0_tb_behav -key {Behavioral:sim_1:Functional:adc_to_udp_stream_v1_0_tb} -tclbatch adc_to_udp_stream_v1_0_tb.tcl -view /home/nrainvil/git/rfsoc_qsfp_10g/boards/RFSoC4x2/udp_stream_v1_0_tb_behav.wcfg -log simulate.log"
xsim adc_to_udp_stream_v1_0_tb_behav -key {Behavioral:sim_1:Functional:adc_to_udp_stream_v1_0_tb} -tclbatch adc_to_udp_stream_v1_0_tb.tcl -view /home/nrainvil/git/rfsoc_qsfp_10g/boards/RFSoC4x2/udp_stream_v1_0_tb_behav.wcfg -log simulate.log

